"""Import every model so `Base.metadata` is complete before create_all/Alembic runs."""

from app.db.base import Base
from app.models.clinical import (
    Condition,
    Document,
    Encounter,
    Prescription,
    PrescriptionItem,
    Surgery,
    TestRequest,
    TimelineEvent,
    VitalReading,
)
from app.models.finance import (
    ClaimDocument,
    InsuranceClaim,
    PatientPolicy,
    Payment,
    Subscription,
)
from app.models.identity import (
    Allergy,
    CareTeamLink,
    DoctorProfile,
    PatientProfile,
    User,
)
from app.models.orders import (
    Appointment,
    EmergencyRequest,
    LabOrder,
    LabOrderItem,
    LabReport,
    LabReportValue,
    MedicineOrder,
    MedicineOrderItem,
)
from app.models.providers import (
    Hospital,
    InsurancePlan,
    Insurer,
    Lab,
    LabTest,
    Pharmacy,
    PharmacyItem,
)
from app.models.social import (
    ChatbotMessage,
    ChatMessage,
    ChatParticipant,
    ChatThread,
    MLRecommendation,
    Notification,
    Post,
    Reminder,
    ReminderLog,
    Review,
)

__all__ = [
    "Base",
    "Allergy",
    "Appointment",
    "CareTeamLink",
    "ChatMessage",
    "ChatParticipant",
    "ChatThread",
    "ChatbotMessage",
    "ClaimDocument",
    "Condition",
    "Document",
    "DoctorProfile",
    "EmergencyRequest",
    "Encounter",
    "Hospital",
    "InsuranceClaim",
    "InsurancePlan",
    "Insurer",
    "Lab",
    "LabOrder",
    "LabOrderItem",
    "LabReport",
    "LabReportValue",
    "LabTest",
    "MLRecommendation",
    "MedicineOrder",
    "MedicineOrderItem",
    "Notification",
    "PatientPolicy",
    "PatientProfile",
    "Payment",
    "Pharmacy",
    "PharmacyItem",
    "Post",
    "Prescription",
    "PrescriptionItem",
    "Reminder",
    "ReminderLog",
    "Review",
    "Subscription",
    "Surgery",
    "TestRequest",
    "TimelineEvent",
    "User",
    "VitalReading",
]
